version: '3'
services:
# mysql
  mysql:
    image: "idoall/mysql:5.6"
    hostname: mysql
    ports:
      - "3306"
    networks:
      - walle-idoall-org
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=walle-web
      - MYSQL_USER=idoall
      - MYSQL_PASSWORD=123456
    depends_on:
      - memcached
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
# walle
  walle:
    image: "idoall/walle-web:1.9"
    hostname: walle
    ports:
      - "80:80"
      - "2222:22"
    networks:
      - walle-idoall-org
    depends_on:
      - mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
# 统一网络设置
networks:
  walle-idoall-org:
    driver: overlay