version: '3'
services:
  walle:
    image: "idoall/walle-web:1.9"
    ports:
     - "80:80"
     - "2222:22"
    networks:
      - tsy-fored
      - tsy-backend
    depends_on:
     - mysql
# mysql
  mysql:
    image: "idoall/mysql:5.6"
    hostname: mysql
    ports:
     - "3306"
    networks:
      - tsy-backend
    volumes:
      - ./walle-web-db:/home/work/_app/mysql/data/
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=walle-web
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
# 统一网络设置
networks:
  tsy-fored:
    driver: overlay
  tsy-backend:
    driver: overlay